// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BrandLogo: typeof import('./src/components/BrandLogo.vue')['default']
    BrandLogoo: typeof import('./src/components/brand-logoo.vue')['default']
    CarbonCampsite: typeof import('virtual:vite-icons/carbon/campsite')['default']
    CarbonDicomOverlay: typeof import('virtual:vite-icons/carbon/dicom-overlay')['default']
    CarbonLanguage: typeof import('virtual:vite-icons/carbon/language')['default']
    CarbonLogoGithub: typeof import('virtual:vite-icons/carbon/logo-github')['default']
    CarbonMoon: typeof import('virtual:vite-icons/carbon/moon')['default']
    CarbonPedestrian: typeof import('virtual:vite-icons/carbon/pedestrian')['default']
    CarbonSun: typeof import('virtual:vite-icons/carbon/sun')['default']
    CarbonWarning: typeof import('virtual:vite-icons/carbon/warning')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    FeatherShoppingCart: typeof import('virtual:vite-icons/feather/shopping-cart')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    'Mdi:bookOpenOutline': typeof import('virtual:vite-icons/mdi/book-open-outline')['default']
    'Mdi:cart': typeof import('virtual:vite-icons/mdi/cart')['default']
    'Mdi:comment': typeof import('virtual:vite-icons/mdi/comment')['default']
    'Mdi:instagram': typeof import('virtual:vite-icons/mdi/instagram')['default']
    'Mdi:plus': typeof import('virtual:vite-icons/mdi/plus')['default']
    'Mdi:whatsapp': typeof import('virtual:vite-icons/mdi/whatsapp')['default']
    MdiShopping: typeof import('virtual:vite-icons/mdi/shopping')['default']
    README: typeof import('./src/components/README.md')['default']
  }
}

export { }
