// generated by vite-plugin-components
// read more https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    BrandLogo: typeof import('./src/components/BrandLogo.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    'Mdi:bookOpenOutline': typeof import('virtual:vite-icons/mdi/book-open-outline')['default']
    'Mdi:chevronDown': typeof import('virtual:vite-icons/mdi/chevron-down')['default']
    'Mdi:comment': typeof import('virtual:vite-icons/mdi/comment')['default']
    'Mdi:home': typeof import('virtual:vite-icons/mdi/home')['default']
    'Mdi:instagram': typeof import('virtual:vite-icons/mdi/instagram')['default']
    'Mdi:menuDown': typeof import('virtual:vite-icons/mdi/menu-down')['default']
    'Mdi:whatsapp': typeof import('virtual:vite-icons/mdi/whatsapp')['default']
  }
}

export { }
